language: python

python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"

before_install:
 - sudo apt-get install lua5.1
 - sudo apt-get install liblua5.1-dev

install: "pip install -r requirements.txt"

script: nosetests
